### PR TITLE
Adding conversion function converting NMEA date/time to POSIX timestamp

### LINKED ISSUE #20: Provide conversion function from RMC Date/Time struct to POSIX timestamp
The $GPRMC dataset also contains the date. Until now this is not yet decoded. So please add this feature.

At the moment time information is returned in 3 variables containing hours, minutes and seconds. Including the date this will be 6 variables. This is not very comfortable if you want to pass the time information on to other functions. Maybe you could combine these functions all in one variable or structure. Maybe as integer like in the unix timestamp.

### PR DESCRIPTION
**Pull request by aentinger**
This fixes #20. @generationmake can you take a look that this is what you want?

### CODE REVIEW

**Comment by aentinger** [comment]
Good morning @generationmake :wave: :coffee: I've rebased this PR after the merge of #22. Can you please have a look if this fulfils requirements stated in #20?

**Comment by generationmake** [comment]
Hi @aentinger 
I don't know if I am using this function correctly. Maybe I need an additional example.

I added the lines:
`  time_t posix_timestamp = nmea::util::toPosixTimestamp(rmc.date, rmc.time_utc);
  Serial.println((unsigned int)posix_timestamp);`
to the function 
`void onRmcUpdate(nmea::RmcData const rmc)`
of the example.

But it seems like it doesn't because it always prints 
`4294967295`
and the number doesn't change.

What am I doing wrong?

**Comment by aentinger** [comment]
Good morning @generationmake :wave: :coffee: 

I believe this is the result because one of either your date or time entries still contains the value `-1`. In this case the function [`rk_timegm.c`](https://github.com/107-systems/107-Arduino-NMEA-Parser/blob/date-time-to-posix/src/nmea/util/timegm.c#L58-L69) returns `-1` which is `4294967295` when casted to unsigned int.

To resolve this I'm providing an additional function `isValid(date,time)` to determine whether or not both `date` and `time` value are valid. Only if they are valid they should be fed into `toPosixTimestamp(...)`, e.g.

```C++
if (nmea::isValid(rmc.date, rmc.time))
{
  time_t posix_timestamp = nmea::util::toPosixTimestamp(rmc.date, rmc.time_utc);
  Serial.println((unsigned int)posix_timestamp);
}
```

Please let me know if this solves your problem.

**Comment by generationmake** [comment]
Hi @aentinger 
This could be. I made the test yesterday when pull request #25 was still open and I think I didn't have a full fix.
I will test again.

**Comment by generationmake** [comment]
I made some tests and added it to my GPX logger and it seems to work.

**Review by generationmake — APPROVED** [review]
review positive.
Do we have to list the external time functions in the readme or documentation?

**Comment by aentinger** [comment]
Thank you for the review :+1: I've indeed forgotten to update `keywords.txt` in a while, should be up to date now.

**Pull request merged**
