### PR TITLE
Support GPRMC messages delivered by ublox NEO-6M

### LINKED ISSUE #9: Parser not working with ublox NEO-6M
Hi @aentinger 
I tried the parser with an ublox NEO-6M receiver but unfortunately it didn't work. It seems like GPRMC dataset is formatted a little bit different than expected. Here is a dataset:
$GPRMC,193517.00,A,4837.99895,N,01301.58584,E,0.793,,111020,,,A*7D

Could you have a look on this? Thank you.

### PR DESCRIPTION
**Pull request by aentinger**
This fixes #9.

### CODE REVIEW

**Comment by aentinger** [comment]
@generationmake What started as a couple of simple changes turned into a **major** parser overhaul. Please test and let me know if it works for you now. If it works, please merge.

**Comment by generationmake** [comment]
Hi @aentinger 

it seems like it doesn't work.
Just after startup with no satellite data, the receiver sends
$GPRMC,,V,,,,,,,,,,N*53
parser gives:
[]  LON |  LAT | 0 m/s | 2146959360 °

after time fix:
$GPRMC,141928.00,V,,,,,,,,,,N*7A
[]  LON |  LAT | 0 m/s | 2146959360 °

and after fix:
$GPRMC,142600.00,A,4837.99474,N,01301.53452,E,27.920,247.03,121020,,,A*5A
[]  LON |  LAT | 0 m/s | 1076673025 °
or
$GPRMC,142552.00,A,4838.00120,N,01301.53118,E,8.979,251.88,121020,,,A*6B
[]  LON |  LAT | -1073741824 m/s | 1074952718 °

so it seems like course is uninitialized.
and that somehow data from the parser is not transferred to the main routine.
The code is your NMEA-Basic example, not modified.

**Comment by aentinger** [comment]
Hi @generationmake :wave:

**Comment by generationmake** [comment]
I tested also with Arduino 1.8.13 and it still does not work.

**Comment by aentinger** [comment]
Yes, it's an error in longitude/latitude parsing I believe. Investigating :microscope:

**Comment by aentinger** [comment]
Fixed now @generationmake :pray: please test.

**Comment by generationmake** [comment]
Hi.
I think it is more a problem with the function call:
when I change line 132 in src/ArduinoNmeaParser.cpp to
_on_rmc_update(12.0,3.4, 5.6, 7.8, 9.0);
it still prints
[]  LON |  LAT |  m/s |  °

**Comment by aentinger** [comment]
Allright, but that's not a problem with the NMEA parser but most likely with `snprintf`. What happens if you enlarge the buffer or use constants, e.g.
```C++
char msg[100] = {0};
snprintf(msg, 100, "[%f] %f LON | %f LAT | %f m/s | %f °", 1.0f, 2.0f, 3.0f, 4.0f, 5.0f);
Serial.println(msg);
```
What happens if your `Serial.println()` those values directly? E.g.
```C++
Serial.print("LON = ");
Serial.println(longitude);
```

**Comment by generationmake** [comment]
Ok. it seems like it is a problem with snprintf.
Enlarging the buffer didn't work.
Directly printing the values (Serial.println(longitude);) works.

**Comment by aentinger** [comment]
Okay, I'll fix the snprintf issue in a separate PR. I'm merging this one as it has grown already quite large and unfocused.

**Comment by generationmake** [comment]
Hi @aentinger 
I tested again with the ublox NEO-6M. The code works perfect when there is a GPS fix. Thank you for your efforts.

Although I'm not yet happy with the startup behaviour.

Right after startup the receiver delivers this dataset:
`$GPRMC,,V,,,,,,,,,,N*53`
This generates the following output:
`-1:-1:-1.-1 : LON 52.26 ° | LAT 20.99 ° | VEL nan m/s | HEADING nan °`
So I think we need a valid-Flag in the parser to filter this out.
Additionally longitude and latitude are somehow not initialized correctly. In my opinion they should 0.0 or better nan if there is no fix.

After time fix time is correct but longitude and latitude still have their initial value.
`$GPRMC,112435.00,V,,,,,,,,,,N*7D
11:24:35.0 : LON 52.26 ° | LAT 20.99 ° | VEL nan m/s | HEADING nan °`

Maybe we should move this to a new issue.

I also tested a vintage receiver: RoyalTek RGM-2000
But this one only delivers the $GPGGA and $GPVTG and thus will not be decoded by the parser.

So from my side it is OK to close this pull request.

**Pull request merged**
